### PR TITLE
Added A0 and A1

### PR DESCRIPTION
**Pull request by j-wie**
Solutions for A0 and A1
I used the Apache Commons CLI library to parse command line argument in A1

### CODE REVIEW

**Comment by j-wie** [comment]
Travis gives the following error for my WordCount program: PackagesNotFoundError:The following packages are not available from current channels:- java-sdk. Additionally I don't know how to include the Apache Commons CLI library in my submission.

**Comment by s-will** [comment]
Hi @j-wie, the testing system was broken for java. At least this should be fixed now. I am looking for a clean solution for the apache commons cli lib

**Comment by s-will** [comment]
Hey @j-wie, I figured out how to solve the testing issues in your case. However, I need find some more free time to implement this --- in the meantime, could you test locally, whether the programs produce the required output for the tests? Don't worry anyway, if not everything works until our Thursday meeting.

**Comment by j-wie** [comment]
I fixed some minor issues and the program now produces the required test output locally.

**Comment by s-will** [comment]
Hi @j-wie, this was unfortunately a little tricky. There is still a minor issue left (missing spaces)

**Comment by s-will** [comment]
nope - the other spaces ;)
[ you could revert the last commit, see git revert ]

**Comment by j-wie** [comment]
Yeah I fixed that again ^^. I already changed some comments too so I decided against git revert. 
I don't know what the issue is now. The format is "difference / sum" printed without a new line right?

**Comment by j-wie** [comment]
Finally ^^ It actually needed a newline.

**Comment by j-wie** [comment]
@s-will I think my code is finally ready for review. :) It tried to follow some Java coding conventions, however it's still not very clean.

**Comment by j-wie** [comment]
I've made my comments more Javadoc-like. I'll have a deeper look at Javadoc/HTML for the next submission. :)

**Pull request merged**
