### PR TITLE
Implement replacement of gold pot(s) after a certain number of rounds

### PR DESCRIPTION
**Pull request by s-will**
Implements a change of rules: the gold pot is replaced after a certain number of rounds.

Defines a new parameter
  params.goldPotTimeOut
to control after how many rounds the gold pot is replaced (and its contents are reset to initial contents).
A status variable
  goldPotRemainingRounds
informs players about how many rounds the pot still stays at the current position

### CODE REVIEW

**Comment by s-will** [comment]
Hey @ViennaAPBC/apbc,
what do you think of the rule change (we discussed this last time). Should we merge it. Should we modify it? Please test. Feel free to suggest patches... 
Cheers, S

**Comment by j-wie** [comment]
Hey everyone @ViennaAPBC/apbc -  the rule change seems fine to me. I've also implemented a version where the gold decreases after half of the timeout is reached. If anyone is interested I can upload it. (@s-will what would be the right way to do this? Should I start a new pull request?) 
Should we take into account that multiple gold pots could be present? (as all gold pots are in sync at the moment, robots finding gold pots shorty before the relocation time could lead to two relocations within a short time period)

**Comment by s-will** [comment]
Hi @j-wie, many thanks for checking this out and thanks for the feedback. Even cooler that you wrote your own modification. We could easily merge the two ideas, e.g. by setting a half-life period together with a minimum amount after which the pot is replaced and reinitialized. Can you please push your code to a new branch and pose a PR? I would have a look whether/how to merge in the idea.

Concerning the multiple pots; I tried to keep the code relatively general but as you say pots are currently in sync. Anyway, we will keep playing with a single pot for the moment, so such problems could be resolved later (e.g. next year by others ;))

**Comment by j-wie** [comment]
@s-will  thanks for the feedback :)  I've already pushed a modification to this branch today. It contains a new parameter goldDecrease, which leads to a decrease in gold after half of the timeOut( if set to True.)

I've also implemented a simple workaround for multiple pots: If one pot is found all gold pots are relocated and the timer starts again. 
When only one gold pot is present and goldDecrease is set to False it behaves like your original code. 
I'll add another new parameter to make the decrease time easier to modify.

**Comment by s-will** [comment]
Hi @ViennaAPBC/apbc, the new rule and @j-wie 's extensions look good to me. I am going to merge this. Can someone suggest an update to the README file, which describes the rules, please? (-> then, please open a new PR)

**Pull request merged**
