### PR TITLE
visualization module + lazy robot

### PR DESCRIPTION
**Pull request by martinbagic**
I created a module that visualizes the map as a gif.
Also, I implemented a simple lazy robot that decides not to complete if other robots are much closer to the gold pot.

### CODE REVIEW

**Comment by martinbagic** [comment]
For the visualization module, I had to change the simulator.py in few places.

**Comment by s-will** [comment]
Hi @martinbagic, the visualization looks really cool. Could you add some description on how to use it and what it shows exactly (what are the traces of the robots - do we see how many moves they made in each round?).

There are some issues that make it very hard to see what you actually changed compared to the current master branch (since you did not derive your files from the current master /and/ your editor made some changes to the files like expanding tabs, which should absolutely be avoided in collaborative projects). I try to fix and rebase --- maybe I come back with this...

**Comment by s-will** [comment]
Hi @martinbagic, I merged with the master and see now a little more clearly, what you changed, but the git history is a mess. It would be great, if you could start with a fresh branch from the current master and then introduce your changes in a new commit (without introducing unnecessary white space changes and without checking in 'generated files' like the gifs and the __pycache__.
Also it would be super-cool to have separate commits and pull requests for your player and for the visualization code. Maybe someone can help to make the visualization more convenient to use (e.g. switch it on by command line args and choose target file).

**Comment by martinbagic** [comment]
Hi @s-will! I'm sorry, I still have some trouble using git.
I made changes to total 7 lines in the simulator.py: 1 for importing the Illustrator class and 6 which all start with self.illustrator. Other changes must be due to a reformatting plugin that I have in VS code. I will clean it up and separate it as you say.

Regarding the visualization - it only visualizes the final positions at each round (so for now, we cannot see the multiple steps individually). Robots are diamonds, the goldpots are stars. The size of the robots and the goldpots grow as their money grows. The robots' colors change from blue to red as their health drops. The colored trails depict the robots' previous 5 positions. I thought it could help give us a better feel for the way the robots moves, plus it signals the identity of the robots since the diamond color already signals the health status and using different icons for different robots was not as visually straightforward.

**Comment by s-will** [comment]
Hi Martin, don't misunderstand - it's great what you did and I don't blame you for the difficulties with git. My idea was mostly that if you can separate it and make the history cleaner, we can share the viz with the other -- maybe someone can help to improve this further.
(Also, this is a good git exercise for you ;))

Thanks for taking care of this and Cheers

**Comment by martinbagic** [comment]
Hi, @s-will, I separated the robot and illustrator but I created a new branch for the robot instead of using this one. How can I overwrite this branch with content from martinbagic#A6robots and delete the robots branch? Or should I just delete this one?

**Comment by s-will** [comment]
Hi @martinbagic, to effectively overwrite this branch you can just delete it (after closing the PR) on github (as long as you have all the changes locally) and then push again from our local repository to github using the same name.

Be aware: deleting and overwriting branches in this way could cause problems, if several people work on the same branch -- in this case, this is ok, since the branch is effectively private.

**Pull request closed without merging**
