### PR TITLE
Illustrator

### PR DESCRIPTION
**Pull request by martinbagic**

### CODE REVIEW

**Comment by s-will** [comment]
Hi @martingbagic, I am looking at the code. I like that now the code still produces the same output as without your modification + the cool visualization.

Hey @ViennaAPBC/apbc: have a look at the viz---this is really cool:)  [check out the branch, make a directory 'Illustrations', and start runRobotRace.py; after playing the game, this produces an animated gif of the match in 'Illustrations']

A nice small modification would be to make the viz optional (and let the user choose a filename). Can you change the code, such that the you modfied Simulator class accepts an additional variable like
```
sim = Simulator(map=m, vizfile='Illustrations/illustration_test.gif')
```
which defaults to None (in which case, no gif is produced)
[Currently there is a small bug: the code assumes that subdirectory Illustrations is present; this would be resolved by such an extension implicitly.]

Then, we should anyway introduce command line arguments for the runRobotRace script to make it more flexible (@ViennaAPBC/apbc: may someone else wants to do this in a separate branch and file a PR).

**Comment by s-will** [comment]
Hi @martinbagic, also many thanks for cleaning up the history; the changes can now be seen very cearly. 

The illustrator gets the current status of the robots and the pot after each round; it seems that you encode health status and gold in the viz, right? I still don't know exactly what the trails show --- is this something like the last 5 positions? What if robots move more quickly? Shouldn't we display the single moves then?

Anyway, I think as soon as viz is optional, we can merge it (I would like to make it optional, since the computation of the gif takes a lot of time)

**Comment by martinbagic** [comment]
Hi, @s-will! Yes, the illustrator is saving the data from the end of each round, thus only the terminal positions are shown and not every step. The trail show the positions from the last 5 rounds. I did it so, because I found it simpler to code it like that, and was not sure if this would make a large difference for the animation. Should I change that?
Also, I will make the changes to make the viz optional. Thank you for the suggestions!

**Comment by s-will** [comment]
Hi @martinbagic. Actually, it would be interesting to see the true path, once the robots start to make more move per round. However, you are right, that it is (probably a lot) easier to implement in the current way.
Currently, the moves are only visible in Simulator._handle_moving():
  - movesPerPlayer is an array which contains a list of moves per player. These are the moves chosen by the players, i.e.
    movesPerPlayer[pId][k] is the kth move of player pId
  - moveStatusPerPlayer[pId][k] is the status of the kth move of player pId; only the moves with status MoveStatus.Done were performed. (You can get the meaning of the other values in the method _handle_moving and game_utils.MoveStatus).
An easy and clean way to make these things available outside of the method would be to return the lists.

**Comment by s-will** [comment]
Hi @martingbagic, I am going to merge in the new code (mines, gold pot expiry). In principle, this should not break your viz. (even if mines will not be visualized automatically - and it would be cool to get this)

**Comment by s-will** [comment]
oh, travis tests your submissions now -- this was not my intention (you could mark the tests as checked, if this gets too annoying)

**Pull request merged**
